stages:
  - build

build_project:
  stage: build
  script:
    - xcodebuild clean -project carbon-footprint-tracking.xcodeproj -scheme SchemeName | xcpretty
    - xcodebuild test -project carbon-footprint-tracking.xcodeproj -scheme SchemeName -destination 'platform=iOS Simulator,name=iPhone 11,OS=13.0' | xcpretty -s
  tags:
    - carbon
